version: '3.8'

services:
  auth-service:
    build:
      context: ../auth-service
    container_name: auth-service
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/AuthData      
      - JWT_SECRET=baudelaire
    networks:
      - app-network
    depends_on:
      - mongo
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth-service.rule=PathPrefix(`/auth`)"
      - "traefik.http.services.auth-service.loadbalancer.server.port=3000"
    volumes:  # This line should be correctly indented
      - ../auth-service:/app

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - app-network
    volumes:
      - mongo-data:/data/db

  traefik:
    image: traefik:v2.5
    container_name: traefik
    ports:
      - "8080:80"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - app-network
    depends_on:
      - auth-service

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
