version: '3'
services:
  restaurant-api:
    build: ./services/restaurant_service
    ports:
      - '3001:3001'
    env_file:
      - ./services/restaurant_service/.env
    depends_on:
      - restaurant-mongo

  restaurant-mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./mongo-data/restaurant:/data/db

volumes:
  mongo-data-restaurant:
