version: '3'
services:
  restaurant-api:
    build: ./services/restaurant_service
    ports:
      - '3001:3001'
    env_file:
      - ./services/restaurant_service/.env
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - restaurant-mongo

  restaurant-mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./mongo-data/restaurant:/data/db

  # user-api:
  #   build: ./services/user_service
  #   ports:
  #     - '3002:3002'
  #   env_file:
  #     - ./services/user_service/.env
  #   volumes:
  #     - ./uploads:/app/uploads
  #   depends_on:
  #     - user-mongo

  # user-mongo:
  #   image: mongo
  #   ports:
  #     - '27018:27017'
  #   volumes:
  #     - ./mongo-data/user:/data/db

  order-api:
    build: ./services/order_service
    ports:
      - '3003:3003'
    env_file:
      - ./services/order_service/.env
    # volumes:
    #   - ./uploads:/app/uploads
    depends_on:
      - order-mongo

  order-mongo:
    image: mongo
    ports:
      - '27019:27017'
    volumes:
      - ./mongo-data/order:/data/db

  cart-api:
    build: ./services/cart_service
    ports:
      - '3004:3004'
    env_file:
      - ./services/cart_service/.env
    # volumes:
    #   - ./uploads:/app/uploads
    depends_on:
      - cart-mongo

  cart-mongo:
    image: mongo
    ports:
      - '27020:27017'
    volumes:
      - ./mongo-data/cart:/data/db

  delivery-api:
    build: ./services/delivery_service
    ports:
      - '3005:3005'
    env_file:
      - ./services/delivery_service/.env
    # volumes:
    #   - ./uploads:/app/uploads
    depends_on:
      - delivery-mongo

  delivery-mongo:
    image: mongo
    ports:
      - '27021:27017'
    volumes:
      - ./mongo-data/delivery:/data/db